#!/usr/bin/env bash

# Script: tell_the_story_of_passwd
# Description: Displays the story of the /etc/passwd users with relevant information.

while IFS=: read -r username password userid groupid uif homedir command
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $command. $userid's place is protected by the passcode $password, more info about the user here: $uif"
done < /etc/passwd
