#!/usr/bin/env bash

# Script: group_visitors_by_ip_and_http
# Description: Displays the visitors grouped by IP address and HTTP codes in descending order of frequency.

awk '{print $1 " " $9}' < apache-access.log | sort | uniq -c | sort -gr
