#!/usr/bin/env bash
# Display "Best School" 10 times, and on the 9th iteration, display "Best School" and then "Hi".

count=0

while ((count<10)); do
	if ((count==8))
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
