#!/usr/bin/env bash

# Script: loop_luck_messages
# Description: Displays different messages based on the value of 'i'.
#              When 'i' is 4, it displays "bad luck".
#              When 'i' is 8, it displays "good luck".
#              For other values of 'i', it displays "Best School".

i=1

while [ $i -le 10 ]; do
  if [ $i -eq 4 ]; then
    echo "bad luck"
  elif [ $i -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done

