#!/usr/bin/env bash

# Script: superstitious_numbers
# Description: Displays numbers from 1 to 20 with specific messages for certain iterations.
#              - For 'i' equal to 4, it displays "4" and "bad luck from China".
#              - For 'i' equal to 9, it displays "9" and "bad luck from Japan".
#              - For 'i' equal to 17, it displays "17" and "bad luck from Italy".
#              - For other values of 'i', it displays the number only.

i=1

while [ $i -le 20 ]; do
  case $i in
    4)
      echo -e "$i\nbad luck from China"
      ;;
    9)
      echo -e "$i\nbad luck from Japan"
      ;;
    17)
      echo -e "$i\nbad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac
  ((i+=1))
done
