#!/usr/bin/env bash

# Script: display_time
# Description: Displays the time in a 12-hour format with minutes ranging from 1 to 59.

hour=0

while [ $hour -le 12 ]; do
  echo "Hour: $hour"

  minute=1
  while [ $minute -lt 60 ]; do
    echo "$minute"
    ((minute++))
  done

  ((hour++))
done
